@echo off
rem Clawdbot Gateway (v2026.1.25)
set HOME=C:\Users\zouta
set PATH=D:\Git_GitHub\clawdbot\node_modules\.bin;C:\Users\zouta\AppData\Local\pnpm\.tools\pnpm\10.23.0_tmp_11200\node_modules\pnpm\dist\node-gyp-bin;D:\Git_GitHub\clawdbot\node_modules\.bin;C:\Users\zouta\AppData\Local\pnpm\.tools\pnpm\10.23.0\bin;C:\Python313\Scripts\;C:\Python313\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\TortoiseSVN\bin;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;c:\Users\zouta\MyProgram\Cursor\resources\app\bin;C:\Program Files\Lingma\bin;C:\Program Files\NVIDIA Corporation\NVIDIA App\NvDLISR;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Users\zouta\AppData\Roaming\Python\Python313\Scripts;C:\Program Files\Comate\bin;C:\Program Files\dotnet\;C:\Program Files\Git LFS;C:\Program Files\TortoiseGit\bin;C:\Program Files\Go\bin;C:\Program Files\Git\cmd;C:\Program Files\Docker\Docker\resources\bin;C:\Program Files\Warp\bin;c:\Users\zouta\AppData\Local\Programs\Trae CN\bin;C:\Users\zouta\miniconda3;C:\Users\zouta\miniconda3\Library\mingw-w64\bin;C:\Users\zouta\miniconda3\Library\usr\bin;C:\Users\zouta\miniconda3\Library\bin;C:\Users\zouta\miniconda3\Scripts;C:\Users\zouta\miniforge3;C:\Users\zouta\miniforge3\Library\mingw-w64\bin;C:\Users\zouta\miniforge3\Library\usr\bin;C:\Users\zouta\miniforge3\Library\bin;C:\Users\zouta\miniforge3\Scripts;C:\Users\zouta\AppData\Local\Microsoft\WindowsApps;C:\Users\zouta\AppData\Roaming\npm;C:\Users\zouta\MyProgram\Cursor\resources\app\bin;C:\Users\zouta\.dotnet\tools;C:\Users\zouta\MyProgram\Microsoft VS Code Insiders\bin;C:\Users\zouta\MyProgram\Qoder\bin;C:\Users\zouta\MyProgram\CodeBuddy CN\bin;C:\Users\zouta\AppData\Local\Programs\Zed\bin;C:\Users\zouta\AppData\Local\Microsoft\WindowsApps;C:\AppData\Programs\CodeBuddy\bin;C:\Users\zouta\.dotnet\tools;C:\Users\zouta\AppData\Local\Programs\Windsurf\bin;C:\Users\zouta\AppData\Local\Programs\Antigravity\bin;C:\Users\zouta\go\bin;;C:\Users\zouta\AppData\Local\Programs\Ollama;C:\Users\zouta\.lmstudio\bin;C:\Users\zouta\AppData\Local\Programs\Kiro\bin
set CLAWDBOT_GATEWAY_PORT=18789
set CLAWDBOT_GATEWAY_TOKEN=259244601b41a0710fef58b4f9c008ff9b2db617c0156dfd
set CLAWDBOT_SYSTEMD_UNIT=clawdbot-gateway.service
set CLAWDBOT_SERVICE_MARKER=clawdbot
set CLAWDBOT_SERVICE_KIND=gateway
set CLAWDBOT_SERVICE_VERSION=2026.1.25
"C:\Program Files\nodejs\node.exe" D:\Git_GitHub\clawdbot\dist\entry.js gateway --port 18789
